// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiPeU3ZwCbwB3RdSkrFwTATo-2q1fU9CM',
    appId: '1:683449264474:web:8f1a2b3c4d5e6789abcdef',
    messagingSenderId: '683449264474',
    projectId: 'kisan-project-gcp',
    authDomain: 'kisan-project-gcp.firebaseapp.com',
    storageBucket: 'kisan-project-gcp.firebasestorage.app',
    measurementId: 'G-ABCD123456',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPeU3ZwCbwB3RdSkrFwTATo-2q1fU9CM',
    appId: '1:683449264474:android:1a2b3c4d5e6f7890abcdef',
    messagingSenderId: '683449264474',
    projectId: 'kisan-project-gcp',
    storageBucket: 'kisan-project-gcp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPeU3ZwCbwB3RdSkrFwTATo-2q1fU9CM',
    appId: '1:683449264474:ios:76133e2c39c14b56b96b63',
    messagingSenderId: '683449264474',
    projectId: 'kisan-project-gcp',
    storageBucket: 'kisan-project-gcp.firebasestorage.app',
    iosBundleId: 'com.kisan.app.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiPeU3ZwCbwB3RdSkrFwTATo-2q1fU9CM',
    appId: '1:683449264474:ios:76133e2c39c14b56b96b63',
    messagingSenderId: '683449264474',
    projectId: 'kisan-project-gcp',
    storageBucket: 'kisan-project-gcp.firebasestorage.app',
    iosBundleId: 'com.kisan.app.frontend',
  );
}
